# File: .github/workflows/azure-static-web-apps.yml

name: Azure Static Web Apps CI/CD new 2

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and build application
      run: |
        npm install
        npm run build

    - name: Package artifacts
      id: package_dev
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build

    - name: Deploy to dev environment
      env:
        REACT_APP_NAME: ${{ secrets.REACT_APP_DEV_URL }}
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: '/'
        api_location: ''
        output_location: '$GITHUB_WORKSPACE/build'  # Use the build artifacts

  build_and_deploy_test:
    runs-on: ubuntu-latest
    needs: build_and_deploy_dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: build

    - name: Deploy to test environment
      env:
        REACT_APP_NAME: ${{ secrets.REACT_APP_TEST_URL }}
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TEST }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: '/'
        api_location: ''
        output_location: '$GITHUB_WORKSPACE/build'  # Use the same build artifacts